on:
 push:
   tags:
     - '!refs/tags/*'
   branches:
     - '*'

jobs:
  req:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with:
          python-version: '3.10.19'
          architecture: 'x64'
      - name: Install requirements
        run: pip install -r requirements.txt

  run_tests:
    needs: req
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with:
          python-version: '3.10.19'
          architecture: 'x64'
	  - name: run_serv
            env:
              GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            run: | gh workflow run run_serv.yml --ref main
	  - name: wait for serv
        uses: jakejarvis/wait-action@v0.1.1
        with:
        time: '10s'
      - name: Run tests
        run: coverage run tests.py
      - name: Tests report
        run: coverage report